# Use root/kys as user/password credentials
version: "3.8"

services:
  mongo:
    image: mongo
    restart: "unless-stopped"
    container_name: "elo-mongo"
    environment:
      MONGO_INITDB_DATABASE: elo-rankings
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kys
    volumes:
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - "./mongodb:/data/db"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kys
  elo-bot:
    image: krissrex/discord-elo-bot
    depends_on:
      - mongo
    links:
      - mongo:mongo
    environment:
      # Modify the values in the .env file
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      MONGO_URI: ${MONGO_URI}
